# semantic_evaluation: 
#   common_root_path: /mnt/cluster-data-all/t006d/nnunetv2/test_data_folder
#   runs:
#     - semantic_pd_path: test_set_SPACE/task590_mms_predsTs
#       semantic_gt_path: test_set_SPACE/labelsTs_Sequence_MPRAGE
#       output_path: test_set_SPACE/task590_mms_predsTs/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: test_set_SPACE/task570_mss_predsTs
#       semantic_gt_path: test_set_SPACE/labelsTs_Sequence_MPRAGE
#       output_path: test_set_SPACE/task570_mss_predsTs/nneval
#       classes_of_interest: 1

#     - semantic_pd_path: test_set_MPRAGE/task561_mmm_predsTs
#       semantic_gt_path: test_set_MPRAGE/labelsTs_Sequence_MPRAGE
#       output_path: test_set_MPRAGE/task561_mmm_predsTs/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: test_set_MPRAGE/task610_msm_predsTs
#       semantic_gt_path: test_set_MPRAGE/labelsTs_Sequence_MPRAGE
#       output_path: test_set_MPRAGE/task610_msm_predsTs/nneval
#       classes_of_interest: 1

#     - semantic_pd_path: stanford_bm/task561_mmm_15
#       semantic_gt_path: stanford_bm/labelsTr
#       output_path: stanford_bm/task561_mmm_15/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: stanford_bm/task570_mss
#       semantic_gt_path: stanford_bm/labelsTr
#       output_path: stanford_bm/task570_mss/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: yale_bm/task561_mmm_15
#       semantic_gt_path: yale_bm/labelsTr
#       output_path: yale_bm/task561_mmm_15/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: yale_bm/task570_mss
#       semantic_gt_path: yale_bm/labelsTr
#       output_path: yale_bm/task570_mss/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: brain_tr_gammaknife/task561_mmm_15
#       semantic_gt_path: brain_tr_gammaknife/labelsTr
#       output_path: brain_tr_gammaknife/task561_mmm_15/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: brain_tr_gammaknife/task570_mss
#       semantic_gt_path: brain_tr_gammaknife/labelsTr
#       output_path: brain_tr_gammaknife/task570_mss/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: all_institutional_hd_bm/task561_mmm_15
#       semantic_gt_path: all_institutional_hd_bm/labelsAll
#       output_path: all_institutional_hd_bm/task561_mmm_15/nneval
#       classes_of_interest: 1
#     - semantic_pd_path: all_institutional_hd_bm/task570_mss
#       semantic_gt_path: all_institutional_hd_bm/labelsAll
#       output_path: all_institutional_hd_bm/task570_mss/nneval
#       classes_of_interest: 1
# instance_generation:
#   common_root_path: /mnt/cluster-data-all/t006d/nnunetv2/test_data_folder
#   runs: 
#     - semantic_labels_path: test_set_SPACE/task590_mms_predsTs
#     - semantic_labels_path: test_set_SPACE/task570_mss_predsTs
#     - semantic_labels_path: test_set_SPACE/labelsTs_Sequence_MPRAGE
      
#     - semantic_labels_path: test_set_MPRAGE/task561_mmm_predsTs
#     - semantic_labels_path: test_set_MPRAGE/task610_msm_predsTs
#     - semantic_labels_path: test_set_MPRAGE/labelsTs_Sequence_MPRAGE
#     - semantic_labels_path: stanford_bm/labelsTr
#     - semantic_labels_path: stanford_bm/task561_mmm_15
#     - semantic_labels_path: stanford_bm/task570_mss
#     - semantic_labels_path: yale_bm/task570_mss
#     - semantic_labels_path: yale_bm/labelsTr
#     - semantic_labels_path: yale_bm/task561_mmm_15
#     - semantic_labels_path: all_institutional_hd_bm/task561_mmm_15
#     - semantic_labels_path: all_institutional_hd_bm/labelsAll
#     - semantic_labels_path: all_institutional_hd_bm/task570_mss
#     - semantic_labels_path: brain_tr_gammaknife/task561_mmm_15
#     - semantic_labels_path: brain_tr_gammaknife/labelsTr
#     - semantic_labels_path: brain_tr_gammaknife/task570_mss

instance_evaluation:
  common_root_path: /mnt/cluster-data-all/t006d/nnunetv2/test_data_folder
  runs:
    - instance_pd_path: test_set_SPACE/task590_mms_predsTs/nneval/pd_instances
      instance_gt_path: test_set_SPACE/labelsTs_Sequence_MPRAGE/nneval/gt_instances
      output_path: test_set_SPACE/task590_mms_predsTs/nneval
      classes_of_interest: 1
    - instance_pd_path: test_set_SPACE/task570_mss_predsTs/nneval/pd_instances
      instance_gt_path: test_set_SPACE/labelsTs_Sequence_MPRAGE/nneval/gt_instances
      output_path: test_set_SPACE/task570_mss_predsTs/nneval
      classes_of_interest: 1

    - instance_pd_path: test_set_MPRAGE/task561_mmm_predsTs/nneval/pd_instances
      instance_gt_path: test_set_MPRAGE/labelsTs_Sequence_MPRAGE/nneval/gt_instances
      output_path: test_set_MPRAGE/task561_mmm_predsTs/nneval
      classes_of_interest: 1
    - instance_pd_path: test_set_MPRAGE/task610_msm_predsTs/nneval/pd_instances
      instance_gt_path: test_set_MPRAGE/labelsTs_Sequence_MPRAGE/nneval/gt_instances
      output_path: test_set_MPRAGE/task610_msm_predsTs/nneval
      classes_of_interest: 1

    - instance_pd_path: stanford_bm/task561_mmm_15/nneval/pd_instances
      instance_gt_path: stanford_bm/labelsTr/nneval/gt_instances
      output_path: stanford_bm/task561_mmm_15/nneval
      classes_of_interest: 1
    - instance_pd_path: stanford_bm/task570_mss/nneval/pd_instances
      instance_gt_path: stanford_bm/labelsTr/nneval/gt_instances
      output_path: stanford_bm/task570_mss/nneval
      classes_of_interest: 1

    - instance_pd_path: yale_bm/task561_mmm_15/nneval/pd_instances
      instance_gt_path: yale_bm/labelsTr/nneval/gt_instances
      output_path: yale_bm/task561_mmm_15/nneval
      classes_of_interest: 1
    - instance_pd_path: yale_bm/task570_mss/nneval/pd_instances
      instance_gt_path: yale_bm/labelsTr/nneval/gt_instances
      output_path: yale_bm/task570_mss/nneval
      classes_of_interest: 1
    - instance_pd_path: brain_tr_gammaknife/task561_mmm_15/nneval/pd_instances
      instance_gt_path: brain_tr_gammaknife/labelsTr/nneval/gt_instances
      output_path: brain_tr_gammaknife/task561_mmm_15/nneval
      classes_of_interest: 1
    - instance_pd_path: brain_tr_gammaknife/task570_mss/nneval/pd_instances
      instance_gt_path: brain_tr_gammaknife/labelsTr/nneval/gt_instances
      output_path: brain_tr_gammaknife/task570_mss/nneval
      classes_of_interest: 1
    - instance_pd_path: all_institutional_hd_bm/task561_mmm_15/nneval/pd_instances
      instance_gt_path: all_institutional_hd_bm/labelsAll/nneval/gt_instances
      output_path: all_institutional_hd_bm/task561_mmm_15/nneval
      classes_of_interest: 1
    - instance_pd_path: all_institutional_hd_bm/task570_mss/nneval/pd_instances
      instance_gt_path: all_institutional_hd_bm/labelsAll/nneval/gt_instances
      output_path: all_institutional_hd_bm/task570_mss/nneval
      classes_of_interest: 1